name: Deploy to Server

on:
  push:
    branches:
      - pran-25-10  # Adjust the branch as necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH for connecting to the EC2 instance
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this matches the secret name

      # Run the deployment script on the EC2 instance
      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@www.assessaai.com << 'EOF'
            cd /home/ubuntu/Assessa-24-10-24  # Navigate to the correct directory where deploy.sh is located
            ./deploy.sh pran-25-10  # Execute the deploy script with the branch name as the argument
          EOF
